### ISSUE TITLE
Investigate crash in unit test related to trace API

### ISSUE THREAD

**Issue by arhag** [eosnetworkfoundation/silkworm#50]
Changes we made in the `rawdb::read_body` function introduced in [this](https://github.com/eosnetworkfoundation/silkworm/commit/6d2d7807ca3575169db82f417e3c3bc11448be74) commit  makes unit test "TraceCallExecutor::trace_filter" to crash.

The code was expecting blocks to have two transactions, one system tx at the beginning and one at the end of the block. We don't have that in our node implementation.

**Comment by stephenpdeos** [comment]
Closing as duplicate
