### ISSUE TITLE
Support blockhash in eth_call

### ISSUE THREAD

**Issue by yarkinwho** [eosnetworkfoundation/silkworm#84]
Currently calls like 
```
 {"jsonrpc":"2.0","method":"eth_call","params":[{"data":"0x06fdde03","gas":"0x2faf080","to":"0x4d0bfaf503fe1e229b1b4f8e4fc1952803ec843f"},{"blockHash":"0x7b3df1e2adc7e36da3ee492b53f678cb948af9589ff0cd762b982afe7bd2b0b4"}],"id":243}
```
will fail

this is because current call only accept string as second params not object.

Some clients do send calls in this form, we need to support it.

Edit:

Object is not in spec. But the support for hash string here is also bugged. We need to fix that. See comments for more details.

**Comment by yarkinwho** [comment]
It seems geth currently do not support such parameter format.

Maybe we would not fix this unless we get stronger reasons for it.

**Comment by stephenpdeos** [comment]
Not officially supported by geth, so we will not prioritize this at this time.

**Comment by yarkinwho** [comment]
> Hey there,
> 
> I wanted to bring up this issue again because it's really important for what we're doing. A lot of RPCs support this operation, and we need it to fix a problem with graph-node indexing. We're having an error in graph-node when syncing because of this, and I think making sure this feature works is key for getting more builders into our ecosystem. Remember, graph stuff is super common in blockchain.
> 
> Also, I've got two pictures here that show the RPC isn't reliable enough. On the Goerli chain, at least I get an error back (which means my request reached the node and the node responded). But on this node, I can't even submit my request to the node.
> 
> ![telegram-cloud-document-5-6244261636631194973](https://user-images.githubusercontent.com/74586952/283140888-7c458f8e-a5a9-487b-8b41-a329fa9d26dd.jpg)
> 
> ![telegram-cloud-document-5-6244261636631194976](https://user-images.githubusercontent.com/74586952/283140941-35dd727f-0966-447e-a9c6-db1975d133f5.jpg)

@myro0x But your pic shows the request reaches the node and returns an error. 

You can argue that maybe we should return some other errors but it indeeds reached the node and got the response.

**Comment by yarkinwho** [comment]
Do you have control on the code sending the request? Simply change {"blockHash":"0x7b3df1e2adc7e36da3ee492b53f678cb948af9589ff0cd762b982afe7bd2b0b4"} to "0x7b3df1e2adc7e36da3ee492b53f678cb948af9589ff0cd762b982afe7bd2b0b4" should make thing work.

**Comment by myro0x** [comment]
I tried to call the USDT contract in testnet for testing this `eth_call`

```bash
curl --request POST \
  --url https://api.testnet.evm.eosnetwork.com \
  --header 'Content-Type: application/json' \
  --data '{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x9fC25190baC66D7be4639268220d1Bd363ca2698","data":"0x06fdde03"},"0x144a827da94cbff85bf690786607acce2af9dc2e9bc7904d3b839a526834d293"],"id":1}'
  ```
  
  i got error 
  `{"jsonrpc":"2.0","id":1,"error":{"code":100,"message":"stol"}}`
  
  using this,
  
  ```bash

curl --request POST \
  --url https://api.testnet.evm.eosnetwork.com \
  --header 'Content-Type: application/json' \
  --data '{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x9fC25190baC66D7be4639268220d1Bd363ca2698","data":"0x06fdde03"},{"blockHash": "0x144a827da94cbff85bf690786607acce2af9dc2e9bc7904d3b839a526834d293"}],"id":1}'
```

i got error 
`{"error":{"code":100,"message":"[json.exception.type_error.302] type must be string, but is object"},"id":1,"jsonrpc":`

If I do this sort of stuff in other chain (using other RPC), it works well.
I guess it might be one of the causes that made my graph-node can't be running properly. 

In my opinion, it will be make this node more reliable too if it can handle this type of operation to handle further problems that might happen because of this

**Comment by yarkinwho** [comment]
> I tried to call the USDT contract in testnet for testing this `eth_call`
> 
> ```shell
> curl --request POST \
>   --url https://api.testnet.evm.eosnetwork.com \
>   --header 'Content-Type: application/json' \
>   --data '{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x9fC25190baC66D7be4639268220d1Bd363ca2698","data":"0x06fdde03"},"0x144a827da94cbff85bf690786607acce2af9dc2e9bc7904d3b839a526834d293"],"id":1}'
> ```
> 
> i got error `{"jsonrpc":"2.0","id":1,"error":{"code":100,"message":"stol"}}`
> 
> using this,
> 
> ```shell
> curl --request POST \
> --url https://api.testnet.evm.eosnetwork.com \
> --header 'Content-Type: application/json' \
> --data '{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x9fC25190baC66D7be4639268220d1Bd363ca2698","data":"0x06fdde03"},{"blockHash": "0x144a827da94cbff85bf690786607acce2af9dc2e9bc7904d3b839a526834d293"}],"id":1}'
> ```
> 
> i got error `{"error":{"code":100,"message":"[json.exception.type_error.302] type must be string, but is object"},"id":1,"jsonrpc":`
> 
> If I do this sort of stuff in other chain (using other RPC), it works well. I guess it might be one of the causes that made my graph-node can't be running properly.
> 
> In my opinion, it will be make this node more reliable too if it can handle this type of operation to handle further problems that might happen because of this

Seems a bug here...

You can use
'{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x9fC25190baC66D7be4639268220d1Bd363ca2698","data":"0x06fdde03"},"144a827da94cbff85bf690786607acce2af9dc2e9bc7904d3b839a526834d293"],"id":1}'
for now as walkaround
Note there's no "0x" prefix in the hash string.

**Comment by myro0x** [comment]
Can you add support to for this operation too, please? Really need it

`{"blockHash": "0x144a827da94cbff85bf690786607acce2af9dc2e9bc7904d3b839a526834d293"}`

**Comment by yarkinwho** [comment]
> Can you add support to for this operation too, please? Really need it
> 
> `{"blockHash": "0x144a827da94cbff85bf690786607acce2af9dc2e9bc7904d3b839a526834d293"}`

We will fix the code so that it will properly accept {"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x9fC25190baC66D7be4639268220d1Bd363ca2698","data":"0x06fdde03"},"0x144a827da94cbff85bf690786607acce2af9dc2e9bc7904d3b839a526834d293"],"id":1} so that it follows the ethereum specs: https://ethereum.github.io/execution-apis/api-documentation/

I don't think it necessary to support another form of input whose functionality can be fully covered by other format. 

Supporting extra formats would be more like a feature instead of bug fix and this one in particular will require some extensive modification to the existing parser code. I believe stronger reasons are needed to justify such feature requests.

**Comment by myro0x** [comment]
Hey, saw this update already applied on latest rpc testnet and it works well!

Now, I can run my graph-node without error, but actually it returns me an EMPTY response instead of the error (same as if you try to run with this op https://github.com/eosnetworkfoundation/silkworm/issues/84#issuecomment-1813882828 , it will return `0x` only),

So the things I need, still, this node need to support this operation, for making this node reliable enough in graph-node.

I just dont get it why you say this not follows the ethereum specs, I already try 10 rpcs and all of the that nodes support this type of operation, even the new L2 chain. Dont mean anything, just want to give you the idea why this operation is really needed!

**Comment by yarkinwho** [comment]
```
 curl --request POST \
  --url https://api.testnet.evm.eosnetwork.com \
  --header 'Content-Type: application/json' \
  --data '{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x9fC25190baC66D7be4639268220d1Bd363ca2698","data":"0x06fdde03"},"0x144a827da94cbff85bf690786607acce2af9dc2e9bc7904d3b839a526834d293"],"id":1}'
{"jsonrpc":"2.0","id":1,"result":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000045553445400000000000000000000000000000000000000000000000000000000"}
```

**Comment by yarkinwho** [comment]
@myro0x we can continue discussing here #93

**Comment by myro0x** [comment]
> Can you add support to for this operation too, please? Really need it
> 
> `{"blockHash": "0x144a827da94cbff85bf690786607acce2af9dc2e9bc7904d3b839a526834d293"}`

this one returns me empty response, `0x`
