### ISSUE TITLE
Review all block_id string in RPC params

### ISSUE THREAD

**Issue by yarkinwho** [eosnetworkfoundation/silkworm#93]
We need to fix all cases similar to #92. After that maybe we can throw away some old codes that are no longer useful.

Before doing that, we need check the RPC API spec https://ethereum.github.io/execution-apis/api-documentation/

to make sure there's no special cases that we should not optionally parse block_id as hash.

**Comment by yarkinwho** [comment]
In addition, as discussed in #84, we might consider supporting inputs objects: {blockHash: "xxx"} ， at least make sure it returns reasonable errors.

**Comment by yarkinwho** [comment]
Should also take this into account https://github.com/eosnetworkfoundation/eos-evm-contract/issues/542

**Comment by yarkinwho** [comment]
More info: the object input schema may come from this stagnant EIP
https://eips.ethereum.org/EIPS/eip-1898

**Comment by myro0x** [comment]
Yes, following up the previous issue, we need to supporting input objects, for specify the `blockHash` `ethCall`

reference:
https://github.com/eosnetworkfoundation/silkworm/issues/84#issuecomment-1813882828

**Comment by yarkinwho** [comment]
The reason for the object inputs to resulted in ```{"jsonrpc":"2.0","id":1,"result":"0x"}``` response is that this object is implicitly converted to string during parsing. And the parse result is defaulted to 0. So essentially this makes the call to call at block 0. For some reason the result is 0x...

**Comment by yarkinwho** [comment]
Currently, according to spec

eth_getBlockReceipts
eth_getBalance
eth_getStorageAt
eth_getTransactionCount
eth_getCode
eth_getProof
eth_call

is using BlockNumberOrTagOrHash

eth_getBlockByNumber
eth_getBlockTransactionCountByNumber
eth_getTransactionByBlockNumberAndIndex
eth_estimateGas
eth_createAccessList
debug_getRawHeader
debug_getRawBlock
eth_feeHistory

is using BlockNumberOrTag


In the code

debug_accountrange
debug_tracecall
eth_estimategas
eth_getbalance
eth_getcode
eth_gettransactioncount
eth_getstorageat
eth_call
eth_createaccesslist
eth_callBundle
ots_has_code
trace_call
trace_call_many
trace_replay_block_transactions
trace_block

is using BlockNumberOrHash (effectively BlockNumberOrTagOrHash)

We know that BlockNumberOrTagOrHash format is compatible to BlockNumberOrTag, so it's fine to support hash even ethereum only support number.

We can see what we are:

eth_getProof
eth_getBlockReceipts

**Comment by yarkinwho** [comment]
We have not implemented eth_getProof yet

So the missing one is eth_getBlockReceipts

implemented in ParityRpcApi::handle_parity_get_block_receipts

**Comment by yarkinwho** [comment]
double checked and found that
eth_getbalance
eth_getcode
eth_gettransactioncount
eth_getstorageat
is not using BlockNumberOrHash to parse block_id so they also need fix.
